apiVersion: v1
kind: Service
metadata:
  name: quarkus-db
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.5
          args: ["-N", "120"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "restcrud"
            - name: POSTGRES_PASSWORD
              value: "restcrud"
            - name: POSTGRES_DB
              value: "rest-crud"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
