apiVersion: v1
kind: Pod
metadata:
  namespace: controller
  labels:
    app: controller
  name: controller
spec:
  serviceAccountName: controller-sa
  containers:
  - args:
    - controller
    image: controller
    imagePullPolicy: Never
    name: controller
    env:
    - name: PROMETHEUS_HOST
      value: prometheus.default.svc.cluster.local
    - name: PROMETHEUS_PORT
      value: "9090"
    - name: PROMETHEUS_PROTOCOL
      value: http
    - name: OP_MODE
      value: MetricForwarder
    - name: SERVICES_TO_EXCLUDE
      value: "frontend-node-port,kubernetes,frontend-external,prometheus-operated,prometheus-operator,prometheus,redis-cart,quarkus-db"
    - name: CUSTOM_METRIC_PROVIDER_HOST
      value: custom-metrics-apiserver.controller.svc.cluster.local
    - name: CUSTOM_METRIC_PROVIDER_PROTOCOL
      value: http
    - name: CUSTOM_METRIC_PROVIDER_PORT
      value: "80"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
