apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: beyla
  name: beyla
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: beyla
    meta.helm.sh/release-namespace: beyla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: beyla
  name: beyla
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: beyla
    meta.helm.sh/release-namespace: beyla
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: beyla
  name: beyla
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: beyla
    meta.helm.sh/release-namespace: beyla
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla