apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quarkus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quarkus
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Object
    object:
      metric:
        name: response_time
      describedObject:
        apiVersion: v1
        kind: Service
        name: quarkus
      target:
        type: Value
        value: 1.0
---
        
